export const SCREEMS = {
  LOAD: "SCREEMS_LOAD",
  CREATE_SCREEM: "CREATE_SCREEM",
  LOAD_SUCCESS: "SCREEMS_LOAD_SUCCESS",
  LOAD_FAIL: "SCREEMS_LOAD_FAIL",
  DELETE_SCREEM: "DELETE_SCREEM",
};

export const AUTH = {
  AUTHENTICATE: "AUTHENTICATE",
  SET_LOG_OUT: "LOG_OUT",
  IS_AUTHENTICATED: "IS_AUTHENTICATED",
  SET_IS_AUTHENTICATING: "SET_IS_AUTHENTICATING",
  SET_AUTHENTICATION_ERROR: "SET_AUTHENTICATION_ERROR",
  FETCH_USER_INFO: "FETCH_USER_INFO",
  UPDATE_USER_INFO: "UPDATE_USER_INFO",
};

export const USER = {
  REGISTER: "REGISTER",
  REGISTER_CONFIRM: "REGISTER_CONFIRM",
  SET_IS_CREATING_USER: "SET_IS_CREATING_USER",
  SET_IS_ERROR: "SET_IS_ERROR",
};

export const PROFILE = {
  LOAD: "LOAD",
  LOAD_SUCCESS: "LOAD_SUCCESS",
  LOAD_FAIL: "LOAD_FAIL",
  RESET_PROFLE: "RESET_PROFLE",
};

export const UPLOAD = {
  UPLOAD_PICTURE: "UPLOAD_PICTURE",
  IS_PICTURE_UPLOADING: "IS_PICTURE_UPLOADING",
  UPLOAD_PICTURE_SUCCESS: "UPLOAD_PICTURE_SUCCESS",
  UPLOAD_PICTURE_ERROR: "UPLOAD_PICTURE_ERROR",
};

export const UPDATE = {
  UPDATE_DETAILS: "UPDATE_DETAILS",
  IS_DETAILS_UPDATING: "IS_DETAILS_UPDATING",
  UPDATE_DETAILS_SUCCESS: "UPDATE_DETAILS_SUCCESS",
  UPDATE_DETAILS_FAILURE: "UPDATE_DETAILS_FAILURE",
};

export const LIKE = {
  LIKE_SCREEM: "LIKE_SCREEM",
  UNLIKE_SCREEM: "UNLIKE_SCREEM",
  LIKE_FEEDBACK: "LIKE_FEEDBACK",
};

export const TOKEN = {
  SET_TOKEN: "SET_TOKEN",
};
