export const SCREEMS = {
  LOAD: "SCREEMS_LOAD",
  LOAD_SUCCESS: "SCREEMS_LOAD_SUCCESS",
  LOAD_FAIL: "SCREEMS_LOAD_FAIL",
};

export const AUTH = {
  AUTHENTICATE: "AUTHENTICATE",
  SET_LOG_OUT: "LOG_OUT",
  IS_AUTHENTICATED: "IS_AUTHENTICATED",
  SET_IS_AUTHENTICATING: "SET_IS_AUTHENTICATING",
  SET_AUTHENTICATION_ERROR: "SET_AUTHENTICATION_ERROR",
  FETCH_USER_INFO: "FETCH_USER_INFO",
  UPDATE_USER_INFO: "UPDATE_USER_INFO",
};

export const USER = {
  REGISTER: "REGISTER",
  REGISTER_CONFIRM: "REGISTER_CONFIRM",
  SET_IS_CREATING_USER: "SET_IS_CREATING_USER",
  SET_IS_ERROR: "SET_IS_ERROR",
};
